version: '3.8'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
    - cluster.initial_master_nodes=es01
    - xpack.security.enabled=false
    - xpack.security.http.ssl.enabled=false
    ports:
    - 9200:9200
    mem_limit: 1073741824
